add version

diff --git a/.github/workflows/frontend-catalog.yml b/.github/workflows/frontend-catalog.yml
--- a/.github/workflows/frontend-catalog.yml
+++ b/.github/workflows/frontend-catalog.yml
@@ -21,6 +21,8 @@ on:
 jobs:
   build-and-push:
     runs-on: ubuntu-latest
+    outputs:
+      TAG: ${{ steps.version.outputs.TAG }}
     steps:
       - uses: actions/checkout@v4
       - name: Setup Node.js
@@ -52,6 +54,14 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
+      - name: Generate Semantic Version Tag
+        id: version
+        run: |
+          RUN_NUMBER=${{ github.run_number }}
+          NEW_TAG="0.0.$RUN_NUMBER"
+          echo "TAG=$NEW_TAG" >> $GITHUB_OUTPUT
+          echo "Building with image tag: $NEW_TAG"
+
       - name: Copy Dockerfile to root context
         run: cp ./projects/frontend-shell/Dockerfile ./Dockerfile
 
@@ -63,10 +73,7 @@ jobs:
           flavor: |
             prefix=front-catalog-
           tags: |
-            type=ref,event=branch
-            type=ref,event=tag
-            type=sha
-            latest
+            type=semver,pattern={{version}},value=${{ steps.version.outputs.TAG }}
 
       - name: Build and push Docker image
         uses: docker/build-push-action@v6
@@ -101,6 +108,16 @@ jobs:
           echo "${{ secrets.GCP_CREDENTIALS }}" | base64 --decode > /tmp/gcp-credentials.json
           gcloud auth activate-service-account --key-file=/tmp/gcp-credentials.json
           gcloud container clusters get-credentials cluster-tcc-1 --zone southamerica-east1 --project tcc-cluster-k8s
+
+      - name: Update Deployment with New Tag
+        run: |
+          TAG=${{ needs.build-test-push.outputs.TAG }}
+          if [ -z "$TAG" ]; then
+            echo "Error: TAG is empty"
+            exit 1
+          fi
+          sed -i "s|:front-catalog-latest|:front-catalog-$TAG|g" ./.k8s/frontend-catalog/deployment.yml
+          echo "Updated image tag to $TAG in deployment.yml"
 
       - name: Deploy to GKE
         run: |
